import type { Metadata } from "next";
import {geistSans, geistMono} from "@/ui/fonts"
import "./globals.css";
import Footer from "@/components/layout/Footer";


export const metadata: Metadata = {
  title: "e-santé - Medilink SN",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.className} ${geistMono.variable} antialiased text-slate-700`}
      >
        {children}
        {/* <Footer /> */}
      </body>
    </html>
  );
}
